export const films_data = {
  page: 1,
  total_results: 2543,
  total_pages: 128,
  results: [
    {
      popularity: 45.852,
      vote_count: 4115,
      video: false,
      poster_path: '/sKmxFCYGSync2zH94Aukzcp8yYA.jpg',
      id: 345940,
      adult: false,
      backdrop_path: '/rH79sB6Nkx4cMW3JzsUy7wK0rhX.jpg',
      original_language: 'en',
      original_title: 'The Meg',
      genre_ids: [28, 27, 878],
      title: 'En eaux troubles',
      vote_average: 6,
      overview:
        "Missionné par un programme international d'observation de la vie sous-marine, un submersible a été attaqué par une créature gigantesque qu'on croyait disparue. Sérieusement endommagé, il gît désormais dans une fosse, au plus profond de l'océan Pacifique, où son équipage est pris au piège. Il n'y a plus de temps à perdre : Jonas Taylor, sauveteur-plongeur expert des fonds marins, est engagé par un océanographe chinois particulièrement visionnaire, contre l'avis de sa fille Suyin.",
      release_date: '2018-08-09',
    },
    {
      popularity: 30.691,
      vote_count: 6362,
      video: false,
      poster_path: '/wVxZDGjd3rCl6y0ksFIhVsEIMmG.jpg',
      id: 539,
      adult: false,
      backdrop_path: '/kZGaVeXSkkvrpMYvD97sxHj291k.jpg',
      original_language: 'en',
      original_title: 'Psycho',
      genre_ids: [18, 27, 53],
      title: 'Psychose',
      vote_average: 8.4,
      overview:
        "Marion Crane en a assez de ne pouvoir mener sa vie comme elle l'entend. Son travail ne la passionne plus, son amant ne peut l'épouser car il doit verser une énorme pension alimentaire le laissant sans le sou... Mais un beau jour, son patron lui demande de déposer 40 000 dollars à la banque. La tentation est trop grande, et Marion s'enfuit avec l'argent. Très vite la panique commence à se faire sentir. Partagée entre l'angoisse de se faire prendre et l'excitation de mener une nouvelle vie, Marion roule vers une destination qu'elle n'atteindra jamais. La pluie est battante, la jeune femme s'arrête près d'un motel, tenu par un sympathique gérant nommé Norman Bates, mais qui doit supporter le caractère possessif de sa mère. Après un copieux repas avec Norman, Marion prend toutes ses précautions afin de dissimuler l'argent. Pour se délasser de cette journée, elle prend une douche...",
      release_date: '1960-06-22',
    },
  ],
};

export const film_by_id = {
  adult: false,
  backdrop_path: '/rH79sB6Nkx4cMW3JzsUy7wK0rhX.jpg',
  belongs_to_collection: null,
  budget: 150000000,
  genres: [
    {id: 28, name: 'Action'},
    {id: 878, name: 'Science-Fiction'},
    {id: 27, name: 'Horreur'},
  ],
  homepage: 'http://www.themeg.movie/',
  id: 345940,
  imdb_id: 'tt4779682',
  original_language: 'en',
  original_title: 'The Meg',
  overview:
    "Missionné par un programme international d'observation de la vie sous-marine, un submersible a été attaqué par une créature gigantesque qu'on croyait disparue. Sérieusement endommagé, il gît désormais dans une fosse, au plus profond de l'océan Pacifique, où son équipage est pris au piège. Il n'y a plus de temps à perdre : Jonas Taylor, sauveteur-plongeur expert des fonds marins, est engagé par un océanographe chinois particulièrement visionnaire, contre l'avis de sa fille Suyin.",
  popularity: 45.852,
  poster_path: '/sKmxFCYGSync2zH94Aukzcp8yYA.jpg',
  production_companies: [
    {
      id: 56242,
      logo_path: '/1YORRYmg7hgYIgoJek8jU3cykuQ.png',
      name: 'Apelles Entertainment',
      origin_country: 'US',
    },
    {
      id: 48778,
      logo_path: '/tto2UKph873Xh1ytxfNBgCxT8NO.png',
      name: 'Gravity Pictures',
      origin_country: 'CN',
    },
    {
      id: 435,
      logo_path: '/AjzK0s2w1GtLfR4hqCjVSYi0Sr8.png',
      name: 'Di Bonaventura Pictures',
      origin_country: 'US',
    },
    {
      id: 107790,
      logo_path: null,
      name: 'Flagship Entertainment Group',
      origin_country: 'CN',
    },
    {
      id: 56241,
      logo_path: null,
      name: 'Maeday Productions',
      origin_country: '',
    },
    {
      id: 174,
      logo_path: '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png',
      name: 'Warner Bros. Pictures',
      origin_country: 'US',
    },
  ],
  production_countries: [
    {iso_3166_1: 'CN', name: 'China'},
    {iso_3166_1: 'US', name: 'United States of America'},
  ],
  release_date: '2018-08-09',
  revenue: 530243742,
  runtime: 113,
  spoken_languages: [
    {iso_639_1: 'zh', name: '普通话'},
    {iso_639_1: 'en', name: 'English'},
    {iso_639_1: 'ja', name: '日本語'},
    {iso_639_1: 'th', name: 'ภาษาไทย'},
  ],
  status: 'Released',
  tagline: "L'appétit vient en mangeant",
  title: 'En eaux troubles',
  video: false,
  vote_average: 6.0,
  vote_count: 4115,
};

export const genres = [
  {id: 28, name: 'Action'},
  {id: 878, name: 'Science-Fiction'},
  {id: 27, name: 'Horreur'},
];
